plugins:
  blockstack_api:
    client: true
    default: "http://localhost:6270"
  blockstack_id_owns_forum_account:
    client: true
    default: false
  blockstack_id_without_tld_owns_forum_account:
    client: true
    default: false
  blockstack_sync_avatar:
    client: true
    default: false
  blockstack_sync_name:
    client: true
    default: false
  blockstack_sync_description:
    client: true
    default: false
  blockstack_sync_location:
    client: true
    default: false
  blockstack_sync_website:
    client: true
    default: false
